In [3409]:
import pandas as pd

dataset = "muv"
column_names = ['dataset', 'split', 'fewshot', 'seed', 'reg', 'score', 'std']
df = pd.read_csv('MoleculeSTM_results/{}/{}_log.csv'.format(dataset, dataset), names=column_names, header=None)

In [3410]:
seed = " All seed"
# split = " Split:size"
fewshot_num = 50
reg_type = "l2_sp"
reg = " Reg_"+ reg_type + "_"
fewshot = " Fewshot_False_{}".format(fewshot_num)

In [3411]:
import numpy as np
import re
def extract_score(s):
    match = re.search(r'Best Acc:\s*(\d+\.\d+|\d+)', s)
    return float(match.group(1)) if match else None

def extract_std(s):
    match = re.search(r'std:\s*(\d+\.\d+|\d+)', s)
    return float(match.group(1)) if match else None

In [3412]:
split = " Split:random"
# filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & (df['fewshot'] == fewshot) & df['reg'].str.contains("Tune")]
# filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & (df['fewshot'] == fewshot) & df['reg'].str.startswith(" WISE")]
# filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & (df['fewshot'] == fewshot) & df['reg'].str.startswith(" DWISE")]
filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & df['reg'].str.contains(reg) & (df['fewshot'] == fewshot)]
# filtered_df = df[(df['seed'] == " All seed") & (df['fewshot'] == fewshot) & df['reg'].str.contains("LP-FT")]
# filtered_df = filtered_df.iloc[[0, 3, 6, 9, 12]]
filtered_df

,dataset,split,fewshot,seed,reg,score,std
266,Dataset:muv,Split:random,Fewshot_False_50,All seed,Reg_l2_sp_m1.0_h1.0,Best Acc:0.49285,std: 0.04533
317,Dataset:muv,Split:random,Fewshot_False_50,All seed,Reg_l2_sp_m0.1_h0.1,Best Acc:0.44545,std: 0.01604
371,Dataset:muv,Split:random,Fewshot_False_50,All seed,Reg_l2_sp_m0.01_h0.01,Best Acc:0.50213,std: 0.04442

In [3413]:
scores = filtered_df['score'].values
stds = filtered_df['std'].values
extracted_scores = np.array([extract_score(item) for item in scores])
extracted_stds = np.array([extract_std(item) for item in stds])
round(np.max(extracted_scores)*100, 2), round(extracted_stds[np.argmax(extracted_scores)]*100, 2)
# round(np.min(extracted_scores), 3), round(extracted_stds[np.argmin(extracted_scores)], 3)

(50.21, 4.44)

In [3414]:
split = " Split:scaffold"
# filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & (df['fewshot'] == fewshot) & df['reg'].str.contains("Tune")]
# filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & (df['fewshot'] == fewshot) & df['reg'].str.startswith(" WISE")]
# filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & (df['fewshot'] == fewshot) & df['reg'].str.startswith(" DWISE")]
filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & df['reg'].str.contains(reg) & (df['fewshot'] == fewshot)]
# filtered_df = df[(df['seed'] == " All seed") & (df['fewshot'] == fewshot) & df['reg'].str.contains("LP-FT")]
# filtered_df = filtered_df.iloc[[0, 3, 6, 9, 12]]
filtered_df

,dataset,split,fewshot,seed,reg,score,std
258,Dataset:muv,Split:scaffold,Fewshot_False_50,All seed,Reg_l2_sp_m1.0_h1.0,Best Acc:0.49256,std: 0.01030
301,Dataset:muv,Split:scaffold,Fewshot_False_50,All seed,Reg_l2_sp_m0.1_h0.1,Best Acc:0.47990,std: 0.01776
351,Dataset:muv,Split:scaffold,Fewshot_False_50,All seed,Reg_l2_sp_m0.01_h0.01,Best Acc:0.53680,std: 0.02515
559,Dataset:muv,Split:scaffold,Fewshot_False_50,All seed,Reg_l2_sp_m0.001_h0.001,Best Acc:0.61618,std: 0.02074

In [3415]:
scores = filtered_df['score'].values
stds = filtered_df['std'].values
extracted_scores = np.array([extract_score(item) for item in scores])
extracted_stds = np.array([extract_std(item) for item in stds])
round(np.max(extracted_scores)*100, 2), round(extracted_stds[np.argmax(extracted_scores)]*100, 2)
# round(np.min(extracted_scores), 3), round(extracted_stds[np.argmin(extracted_scores)], 3)

(61.62, 2.07)

In [3416]:
split = " Split:size"
# filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & (df['fewshot'] == fewshot) & df['reg'].str.contains("Tune")]
# filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & (df['fewshot'] == fewshot) & df['reg'].str.startswith(" WISE")]
# filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & (df['fewshot'] == fewshot) & df['reg'].str.startswith(" DWISE")]
filtered_df = df[(df['seed'] == " All seed") & (df['split'] == split) & df['reg'].str.contains(reg) & (df['fewshot'] == fewshot)]
# filtered_df = df[(df['seed'] == " All seed") & (df['fewshot'] == fewshot) & df['reg'].str.contains("LP-FT")]
# filtered_df = filtered_df.iloc[[0, 3, 6, 9, 12]]
filtered_df

,dataset,split,fewshot,seed,reg,score,std
256,Dataset:muv,Split:size,Fewshot_False_50,All seed,Reg_l2_sp_m1.0_h1.0,Best Acc:0.52866,std: 0.04439
310,Dataset:muv,Split:size,Fewshot_False_50,All seed,Reg_l2_sp_m0.1_h0.1,Best Acc:0.49582,std: 0.03360
357,Dataset:muv,Split:size,Fewshot_False_50,All seed,Reg_l2_sp_m0.01_h0.01,Best Acc:0.50749,std: 0.02731
563,Dataset:muv,Split:size,Fewshot_False_50,All seed,Reg_l2_sp_m0.001_h0.001,Best Acc:0.58288,std: 0.03741

In [3417]:
scores = filtered_df['score'].values
stds = filtered_df['std'].values
extracted_scores = np.array([extract_score(item) for item in scores])
extracted_stds = np.array([extract_std(item) for item in stds])
round(np.max(extracted_scores)*100, 2), round(extracted_stds[np.argmax(extracted_scores)]*100, 2)
# round(np.min(extracted_scores), 3), round(extracted_stds[np.argmin(extracted_scores)], 3)

(58.29, 3.74)

In [3418]:
scores = filtered_df['score'].values
stds = filtered_df['std'].values
scores, stds

(array([' Best Acc:0.52866', ' Best Acc:0.49582', ' Best Acc:0.50749',
        ' Best Acc:0.58288'], dtype=object),
 array([' std: 0.04439', ' std: 0.03360', ' std: 0.02731', ' std: 0.03741'],
       dtype=object))

In [3419]:
import numpy as np
import re
def extract_score(s):
    match = re.search(r'Best Acc:\s*(\d+\.\d+|\d+)', s)
    return float(match.group(1)) if match else None

def extract_std(s):
    match = re.search(r'std:\s*(\d+\.\d+|\d+)', s)
    return float(match.group(1)) if match else None

# Apply the function to each element in the numpy array
extracted_scores = np.array([extract_score(item) for item in scores])
extracted_stds = np.array([extract_std(item) for item in stds])

In [3420]:
extracted_scores * 100, extracted_stds * 100

(array([52.866, 49.582, 50.749, 58.288]), array([4.439, 3.36 , 2.731, 3.741]))

In [3421]:
extracted_scores, extracted_stds

(array([0.52866, 0.49582, 0.50749, 0.58288]),
 array([0.04439, 0.0336 , 0.02731, 0.03741]))